server:
  port: 9098
  
  
spring:
  kafka:
    bootstrap-servers: "172.20.150.82:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.LongSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://172.20.150.82:8081"
    streams:
      bootstrap-servers: "172.20.150.82:9092"
      application-id: "sp-kafka-stream-demo-1"
    consumer:
      group-id: "group_registrer_new_consumer_1"
      keyDeserializer: "org.apache.kafka.common.serialization.LongDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://172.20.150.82:8081"
        specific:
          avro:
            reader: "true"
schema:
  registry:
    url: "http://172.20.150.82:8081"
          
topic:
  source:
    name: "confluentKafkaCursoLoan"
  sink:
    collateral:
      name: "confluentKafkaCursoLoan.collateral.topic.v1"
    employment:
      name: "confluentKafkaCursoLoan.employment.topic.v1"